version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - 3000:3000
    volumes:
      - /Users/Shared/Deployproducts/warehousetask/src/index.js:/app/index.js
    depends_on:
      - db
  